### ISSUE TITLE
Name is dropped when transforming name-titles as subjects

### ISSUE THREAD

**Issue by shelleydoljack** [LibraryOfCongress/mods2bibframe#13]
If my MODS has a subject that looks like this:
<subject authority="lcsh">
    <name type="personal" authority="naf" authorityURI="http://id.loc.gov/authorities/names" valueURI="http://id.loc.gov/authorities/names/n79041870">
        <namePart>Woolf, Virginia</namePart>
        <namePart type="date">1882-1941</namePart>
    </name>
    <titleInfo authority="naf" authorityURI="http://id.loc.gov/authorities/names" valueURI="http://id.loc.gov/authorities/names/no98043473">
        <title>Mrs. Dalloway</title>
    </titleInfo>
</subject>

I only end up with a bf:Work graph that looks like this:
<bf:Work rdf:about="http://bibframe.org/resources/{#resourceID}">
      <bf:authorizedAccessPoint>Mrs. Dalloway</bf:authorizedAccessPoint>
      <bf:authorizedAccessPoint xml:lang="x-bf-hash">mrsdalloway</bf:authorizedAccessPoint>
      <bf:workTitle rdf:resource="http://bibframe.org/resources/{#resourceID}title8"/>
      <bf:title>Mrs. Dalloway</bf:title>
      <bf:title xml:lang="x-bf-sort">Mrs. Dalloway</bf:title>
      <bf:contributor rdf:resource="http://bibframe.org/resources/{#resourceID}person8"/>
</bf:Work>

I do not have a graph for the resource "person8" in my transformed document.

**Comment by wsalesky** [comment]
This new version should eliminate the erroneous reference to the contributor resource.
